# Database
db_name: wordpress
db_user: wpuser
db_password: wppassword
db_root_password: rootpassword

# WordPress
wp_url: "https://{{ ansible_host }}"
wp_title: "My WordPress Site"
wp_admin_user: admin
wp_admin_password: adminpassword
wp_admin_email: admin@example.com
wp_user: user
wp_user_password: userpassword
wp_user_email: user@example.com

# Paths
app_path: /opt/wordpress
data_path: /opt/data
